"""
SEO router (ECO.NOVA) — centralized, production-grade SEO surfaces.

Everything is generated by the backend/app/seo/ engine package so the site
stays consistent and free of legacy BiBi Cars artifacts:

  GET /api/seo/robots.txt            env-aware robots
  GET /api/seo/sitemap.xml           sitemap INDEX
  GET /api/seo/sitemap-pages.xml     static public pages (+hreflang)
  GET /api/seo/sitemap-catalog.xml   waste categories + codes
  GET /api/seo/sitemap-blog.xml      published articles
  GET /api/seo/sitemap-images.xml    image sitemap
  GET /api/seo/meta                  per-route metadata + JSON-LD (frontend)
  GET /api/seo/runtime-config        public analytics/verification config
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Request, Response, Query

from app.seo import get_origin, canonical_url, hreflang_alternates
from app.seo import robots as robots_engine
from app.seo import sitemap as sm
from app.seo import schema as S
from app.seo import metadata as M

router = APIRouter(prefix="/api/seo", tags=["seo"])

_XML = "application/xml"


def _db(request: Request):
    st = getattr(request.app, "state", None)
    return getattr(st, "db", None) if st is not None else None


async def _company(request: Request) -> Dict[str, Any]:
    """Assemble company facts for JSON-LD from admin-managed settings.

    Never fabricates: unknown fields are simply left empty so schema.py
    omits them. Real EEAT values (license number, geo, founding date) come
    from seo_settings once the operator fills them in.
    """
    db = _db(request)
    company: Dict[str, Any] = {"name": "ECO.NOVA"}
    # Footer / contacts (already admin-managed)
    try:
        from settings_service import get_settings_service  # type: ignore
        footer = await get_settings_service().get_footer()
        contacts = (footer or {}).get("contacts", {})
        comp = (footer or {}).get("company", {})
        phones = contacts.get("phones") or ([contacts.get("phone")] if contacts.get("phone") else [])
        company.update({
            "legal_name": comp.get("legalName"),
            "edrpou": comp.get("edrpou"),
            "phones": [p for p in phones if p],
            "email": contacts.get("email"),
            "street": contacts.get("address"),
            "opening_hours": contacts.get("working_hours"),
        })
    except Exception:
        pass
    # SEO settings (EEAT extras + defaults)
    try:
        if db is not None:
            doc = await db.seo_settings.find_one({"_id": "global"}) or {}
            for k_src, k_dst in [
                ("license_number", "license_number"),
                ("license_name", "license_name"),
                ("company_city", "city"),
                ("company_region", "region"),
                ("company_postal", "postal_code"),
                ("company_lat", "lat"),
                ("company_lng", "lng"),
                ("founding_date", "founding_date"),
                ("default_og_image", "logo"),
                ("default_description", "description"),
                ("same_as", "same_as"),
            ]:
                v = doc.get(k_src)
                if v:
                    company[k_dst] = v
    except Exception:
        pass
    return company


# ─────────────────────────────────────────────────────────────── robots ──
@router.get("/robots.txt", response_class=Response)
async def robots_txt(request: Request) -> Response:
    return Response(
        content=robots_engine.build_robots(request),
        media_type="text/plain",
        headers={"Cache-Control": "public, max-age=3600"},
    )


# ────────────────────────────────────────────────────────────── sitemaps ──
@router.get("/sitemap.xml", response_class=Response)
async def sitemap_index(request: Request) -> Response:
    return Response(content=sm.sitemap_index(request), media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


@router.get("/sitemap-pages.xml", response_class=Response)
async def sitemap_pages(request: Request) -> Response:
    return Response(content=sm.sitemap_pages(request), media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


@router.get("/sitemap-catalog.xml", response_class=Response)
async def sitemap_catalog(request: Request) -> Response:
    xml = await sm.sitemap_catalog(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=1800"})


@router.get("/sitemap-blog.xml", response_class=Response)
async def sitemap_blog(request: Request) -> Response:
    xml = await sm.sitemap_blog(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=1800"})


@router.get("/sitemap-images.xml", response_class=Response)
async def sitemap_images(request: Request) -> Response:
    xml = await sm.sitemap_images(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


# ─────────────────────────────────────────────── per-route metadata + LD ──
@router.get("/meta")
async def route_meta(
    request: Request,
    path: str = Query("/", description="Public route path, e.g. /waste"),
    lang: str = Query("uk"),
) -> Dict[str, Any]:
    """Return everything the frontend <SeoHead> needs for a given route."""
    lang = "en" if (lang or "").lower().startswith("en") else "uk"
    origin = get_origin(request)
    db = _db(request)
    path = path or "/"
    if len(path) > 1 and path.endswith("/"):
        path = path.rstrip("/")

    # Base metadata: static registry, else dynamic resolvers.
    base = M.resolve_static(path, lang, origin)
    extra_nodes: List[Dict[str, Any]] = []
    published = updated = author = image = None

    if base is None:
        # ---- dynamic: /waste/category/{key} ----
        if path.startswith("/waste/category/"):
            key = path.rsplit("/", 1)[-1]
            label = key.replace("-", " ").replace("_", " ").title()
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"category": key}, {"_id": 0, "category": 1})
                    if doc:
                        label = key.replace("_", " ").title()
            except Exception:
                pass
            t = (f"Відходи: {label}" if lang == "uk" else f"Waste: {label}")
            d = (f"Коди та вимоги до поводження з відходами категорії «{label}» за національним класифікатором."
                 if lang == "uk"
                 else f"Codes and handling requirements for the “{label}” waste category under the national classifier.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": label, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /waste-code/{slug} ----
        elif path.startswith("/waste-code/"):
            slug = path.rsplit("/", 1)[-1]
            code = slug.replace("-", " ")
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"slug": slug}, {"_id": 0, "code": 1, "updated_at": 1})
                    if doc:
                        code = doc.get("code") or code
                        updated = doc.get("updated_at")
            except Exception:
                pass
            t = (f"Код відходу {code}" if lang == "uk" else f"Waste code {code}")
            d = (f"Код {code} за національним класифікатором відходів: клас небезпеки, вимоги до пакування, "
                 f"транспортування та методи утилізації."
                 if lang == "uk"
                 else f"Code {code} under the national waste classifier: hazard class, packaging, transport and utilization methods.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": code, "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": code, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /blog/{slug} ----
        elif path.startswith("/blog/"):
            slug = path.rsplit("/", 1)[-1]
            t = slug.replace("-", " ").capitalize()
            d = ""
            try:
                if db is not None:
                    doc = await db.blog_articles.find_one({"slug": slug}, {"_id": 0}) or {}
                    t = doc.get("title") or t
                    d = doc.get("excerpt") or doc.get("summary") or doc.get("description") or ""
                    image = doc.get("cover_image") or doc.get("image")
                    published = doc.get("published_at") or doc.get("created_at")
                    updated = doc.get("updated_at")
                    author = (doc.get("author") or {}).get("name") if isinstance(doc.get("author"), dict) else doc.get("author")
            except Exception:
                pass
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "article",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Блог" if lang == "uk" else "Blog", "url": f"{origin}/blog"},
                        {"name": t, "url": f"{origin}{path}"},
                    ]}
        else:
            # Unknown public path → generic homepage-like metadata (still valid).
            base = M.resolve_static("/", lang, origin)

    canonical = canonical_url(f"{path}?lang=en" if lang == "en" else path, request)
    alternates = hreflang_alternates(path, request)

    # ---- JSON-LD @graph ----
    company = await _company(request)
    url = f"{origin}{path}" if path != "/" else f"{origin}/"
    nodes: List[Dict[str, Any]] = [
        S.organization(company, origin),
        S.website(origin),
        S.web_page(origin, canonical, base["title"], base["description"], lang,
                   published=published, updated=updated,
                   breadcrumb_id=f"{canonical}#breadcrumb"),
    ]
    if base.get("breadcrumbs"):
        nodes.append(S.breadcrumb_list(base["breadcrumbs"], canonical))
    if path == "/":
        nodes.append(S.local_business(company, origin))
    if base.get("is_app"):
        nodes.append(S.software_application(
            origin, canonical, base["title"], base["description"]))
    if base.get("type") == "article":
        nodes.append(S.article(origin, canonical, base["title"], base["description"],
                               image, published, updated, author, lang))
    nodes.extend(extra_nodes)
    jsonld = S.graph(nodes)

    og_image = image or company.get("logo") or (f"{origin}/android-chrome-512x512.png" if origin else "")

    return {
        "path": path,
        "lang": lang,
        "title": base["full_title"],
        "shortTitle": base["title"],
        "description": base["description"],
        "keywords": base.get("keywords", ""),
        "canonical": canonical,
        "robots": "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1",
        "hreflang": alternates,
        "og": {
            "type": base.get("type", "website"),
            "site_name": "ECO.NOVA",
            "title": base["title"],
            "description": base["description"],
            "url": canonical,
            "image": og_image,
            "locale": "uk_UA" if lang == "uk" else "en_US",
            "locale_alternate": "en_US" if lang == "uk" else "uk_UA",
        },
        "twitter": {
            "card": "summary_large_image",
            "title": base["title"],
            "description": base["description"],
            "image": og_image,
        },
        "breadcrumbs": base.get("breadcrumbs", []),
        "published": published,
        "updated": updated,
        "author": author,
        "jsonld": jsonld,
    }


# ─────────────────────────────────────────────────────── runtime config ──
@router.get("/runtime-config")
async def runtime_config(request: Request) -> Dict[str, Any]:
    db = _db(request)
    doc: Dict[str, Any] = {}
    if db is not None:
        try:
            doc = await db.seo_settings.find_one({"_id": "global"}) or {}
        except Exception:
            doc = {}
    return {
        "ga4_measurement_id":       doc.get("ga4_measurement_id") or "",
        "gtm_container_id":         doc.get("gtm_container_id") or "",
        "google_ads_conversion_id": doc.get("google_ads_conversion_id") or "",
        "google_ads_send_page_view": bool(doc.get("google_ads_send_page_view", True)),
        "google_ads_conversion_labels": doc.get("google_ads_conversion_labels") or {},
        "facebook_pixel_id":        doc.get("facebook_pixel_id") or "",
        "google_site_verification": doc.get("google_site_verification") or "",
        "bing_site_verification":   doc.get("bing_site_verification") or "",
        "yandex_site_verification": doc.get("yandex_site_verification") or "",
        "indexnow_key":             doc.get("indexnow_key") or "",
        "default_title":       doc.get("default_title") or "",
        "default_description": doc.get("default_description") or "",
        "default_keywords":    doc.get("default_keywords") or "",
        "default_og_image":    doc.get("default_og_image") or "",
    }


__all__ = ["router"]
